services:
  zhiguang-logstash:
    image: logstash:9.5.1
    container_name: zhiguang-logstash
    restart: unless-stopped
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx512m"
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - onepanel

networks:
  onepanel:
    external: true
    name: 1panel-network
