input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "observer_stack" => "elk"
      "project" => "zhiguang"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "zhiguang-agent-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
